### PR TITLE
OSD-7742: Ensure exporter uses new base image

### PR DESCRIPTION
**Pull request by lisa**
Change to use `latest` image tag.

Depends on openshift/managed-prometheus-exporter-base#5

For [OSD-7742](https://issues.redhat.com/browse/OSD-7742)

Signed-off-by: Lisa Seelye <lisa@users.noreply.github.com>

### CODE REVIEW

**Comment by lisa** [comment]
/hold 

for deps and review

**Review by dkeohane — APPROVED** [review]
:waffle: 
/lgtm

**Review by dkeohane — APPROVED** [review]
/lgtm

**Pull request merged**
